### ISSUE TITLE
Не работает на PhpStorm 2023.1

### ISSUE THREAD

**Issue by 1xtr** [yandex-cloud/ide-plugin-jetbrains#17]
Build #PS-231.8109.199, built on March 30, 2023

```
java.util.ServiceConfigurationError: io.grpc.LoadBalancerProvider: io.grpc.util.OutlierDetectionLoadBalancerProvider not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67)
	at io.grpc.LoadBalancerRegistry.getDefaultRegistry(LoadBalancerRegistry.java:102)
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory.<init>(AutoConfiguredLoadBalancerFactory.java:57)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:580)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:524)
	at yandex.cloud.sdk.auth.provider.OauthCredentialProvider$Builder.providerBuild(OauthCredentialProvider.java:110)
	at yandex.cloud.sdk.auth.provider.AbstractCredentialProviderBuilder.build(AbstractCredentialProviderBuilder.java:40)
	at yandex.cloud.toolkit.api.auth.CloudAuthData$Companion.byOAuthToken(CloudAuthData.kt:48)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$createAuthData$1$1.invoke(OAuthCloudAuthMethod.kt:55)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$createAuthData$1$1.invoke(OAuthCloudAuthMethod.kt:12)
	at yandex.cloud.toolkit.util.MaybeKt.doMaybe(Maybe.kt:67)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$createAuthData$1.invoke(OAuthCloudAuthMethod.kt:54)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$createAuthData$1.invoke(OAuthCloudAuthMethod.kt:12)
	at yandex.cloud.toolkit.util.MaybeKt.map(Maybe.kt:43)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod.createAuthData(OAuthCloudAuthMethod.kt:53)
	at yandex.cloud.toolkit.api.profile.CloudProfile$getAuthData$1.invoke(CloudProfile.kt:94)
	at yandex.cloud.toolkit.api.profile.CloudProfile$getAuthData$1.invoke(CloudProfile.kt:21)
	at yandex.cloud.toolkit.util.remote.resource.RemoteResource.updateState(RemoteResource.kt:42)
	at yandex.cloud.toolkit.api.profile.CloudProfile.getAuthData(CloudProfile.kt:92)
	at yandex.cloud.toolkit.api.resource.impl.model.CloudUser.getAuthData(Cloud.kt:35)
	at yandex.cloud.toolkit.api.resource.impl.model.CloudUser.getChildNodes(Cloud.kt:45)
	at yandex.cloud.toolkit.api.explorer.CloudResourceNode.getChildren(CloudResourceNode.kt:52)
	at com.intellij.ui.treeStructure.SimpleTreeStructure.getChildElements(SimpleTreeStructure.java:12)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:410)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:328)
	at com.intellij.ui.tree.StructureTreeModel$Node.isModelLeaf(StructureTreeModel.java:583)
	at com.intellij.ui.tree.StructureTreeModel.isLeaf(StructureTreeModel.java:364)
	at com.intellij.ui.tree.LeafState.get(LeafState.java:64)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.load(AsyncTreeModel.java:597)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:570)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:464)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:430)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:304)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:107)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:187)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:431)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by ITmind** [comment]
И в PyCharm тоже самое
