### ISSUE TITLE
Не работает в idea 2023.1

### ISSUE THREAD

**Issue by AShipulin** [yandex-cloud/ide-plugin-jetbrains#18]
1. При попытке авторизоваться через CLI получаю бесконечную загрузку 
![image](https://github.com/yandex-cloud/ide-plugin-jetbrains/assets/2566838/a67431fb-92a1-4574-b7b7-37d2cdddbacd)

2. При попытке авторизоваться через OAuth в браузере вижу Authorization successful а в ide получаю 
```
java.util.ServiceConfigurationError: io.grpc.LoadBalancerProvider: io.grpc.util.OutlierDetectionLoadBalancerProvider not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67)
	at io.grpc.LoadBalancerRegistry.getDefaultRegistry(LoadBalancerRegistry.java:102)
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory.<init>(AutoConfiguredLoadBalancerFactory.java:57)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:580)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:524)
	at yandex.cloud.sdk.auth.provider.OauthCredentialProvider$Builder.providerBuild(OauthCredentialProvider.java:110)
	at yandex.cloud.sdk.auth.provider.AbstractCredentialProviderBuilder.build(AbstractCredentialProviderBuilder.java:40)
	at yandex.cloud.toolkit.api.auth.CloudAuthData$Companion.byOAuthToken(CloudAuthData.kt:48)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$createAuthData$1$1.invoke(OAuthCloudAuthMethod.kt:55)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$createAuthData$1$1.invoke(OAuthCloudAuthMethod.kt:12)
	at yandex.cloud.toolkit.util.MaybeKt.doMaybe(Maybe.kt:67)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$createAuthData$1.invoke(OAuthCloudAuthMethod.kt:54)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$createAuthData$1.invoke(OAuthCloudAuthMethod.kt:12)
	at yandex.cloud.toolkit.util.MaybeKt.map(Maybe.kt:43)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod.createAuthData(OAuthCloudAuthMethod.kt:53)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$authenticate$1.invoke(OAuthCloudAuthMethod.kt:34)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$authenticate$1.invoke(OAuthCloudAuthMethod.kt:12)
	at yandex.cloud.toolkit.api.auth.impl.oauth.CloudOAuthServiceImpl$requestToken$1.invoke(CloudOAuthServiceImpl.kt:120)
	at yandex.cloud.toolkit.api.auth.impl.oauth.CloudOAuthServiceImpl$requestToken$1.invoke(CloudOAuthServiceImpl.kt:43)
	at yandex.cloud.toolkit.util.task.TaskBuilderKt$modalTask$1.run(TaskBuilder.kt:139)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by antonydevanchi** [comment]
@AShipulin @socolio может быть закроем ишью?

**Comment by AShipulin** [comment]
Проверил авторизацию OAuth на версии IntelliJ IDEA 2023.1.4 получил ошибку, см. ниже
Авторизация через CLI в бесконечной загрузке.

```
java.util.ServiceConfigurationError: io.grpc.LoadBalancerProvider: io.grpc.util.OutlierDetectionLoadBalancerProvider not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67)
	at io.grpc.LoadBalancerRegistry.getDefaultRegistry(LoadBalancerRegistry.java:102)
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory.<init>(AutoConfiguredLoadBalancerFactory.java:57)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:580)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:524)
	at yandex.cloud.sdk.auth.provider.OauthCredentialProvider$Builder.providerBuild(OauthCredentialProvider.java:110)
	at yandex.cloud.sdk.auth.provider.AbstractCredentialProviderBuilder.build(AbstractCredentialProviderBuilder.java:40)
	at yandex.cloud.toolkit.api.auth.CloudAuthData$Companion.byOAuthToken(CloudAuthData.kt:48)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$createAuthData$1$1.invoke(OAuthCloudAuthMethod.kt:55)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$createAuthData$1$1.invoke(OAuthCloudAuthMethod.kt:12)
	at yandex.cloud.toolkit.util.MaybeKt.doMaybe(Maybe.kt:67)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$createAuthData$1.invoke(OAuthCloudAuthMethod.kt:54)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$createAuthData$1.invoke(OAuthCloudAuthMethod.kt:12)
	at yandex.cloud.toolkit.util.MaybeKt.map(Maybe.kt:43)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod.createAuthData(OAuthCloudAuthMethod.kt:53)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$authenticate$1.invoke(OAuthCloudAuthMethod.kt:34)
	at yandex.cloud.toolkit.api.auth.impl.oauth.OAuthCloudAuthMethod$authenticate$1.invoke(OAuthCloudAuthMethod.kt:12)
	at yandex.cloud.toolkit.api.auth.impl.oauth.CloudOAuthServiceImpl$requestToken$1.invoke(CloudOAuthServiceImpl.kt:120)
	at yandex.cloud.toolkit.api.auth.impl.oauth.CloudOAuthServiceImpl$requestToken$1.invoke(CloudOAuthServiceImpl.kt:43)
	at yandex.cloud.toolkit.util.task.TaskBuilderKt$modalTask$1.run(TaskBuilder.kt:139)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by antonydevanchi** [comment]
Duplicate #17

**Comment by omqmo** [comment]
В последней версии такая же история. Авторизация с помощью OAuth вообще не проходит, а при помощи cli все как на картинке выше.

**Comment by chudno** [comment]
На mac m1 такая же история, ide вылетает после аутентификации.

**Comment by socolio** [comment]
Всем привет. Оказалось, что с определенной версии Intellij Platform тащит с собой либу GRPC. В плагине такая тоже есть, но более старая (увы, обновить не можем, она транзитивная). На неделе постараюсь выкатить фикс, чтобы юзать встроенную версию.

**Comment by sibyakin** [comment]
Всё ещё воспроизводится для GoLand.
